name: Deploy
on:
  schedule:
    - cron: "* 0 * * *"
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Generate
        run: npx nuxt generate
        env:
          NUXT_PUBLIC_CONTACT_EMAIL: ${{ secrets.NUXT_PUBLIC_CONTACT_EMAIL }}
          NUXT_PUBLIC_CONTACT_PHONE: ${{ secrets.NUXT_PUBLIC_CONTACT_PHONE }}
      - name: Install wrangler
        run: npm install --global wrangler
      - name: Copy header rules
        run: cp .cloudflare/headers dist/_headers
      - name: Add last-modified timestamp
        run: sed -i -e "s|<LAST_MODIFIED>|$(date -u +"%a, %d %b %Y %H:%M:%S GMT")|g" dist/_headers
      - name: Deploy
        run: npx wrangler pages deploy dist --project-name frederictonclimatehubca
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}